# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do

  desc "create an ios ipa file in build folder"
  lane :staging do
    match(type: "adhoc")
    add_badge(alpha: true)
    update_project_provisioning(
      xcodeproj: 'ExoRun.xcodeproj',
      profile:ENV["sigh_com.ExoSuite.ExoRun_adhoc_profile-path"],
      build_configuration: "Release"
    )
    gym(
        workspace: "ExoRun.xcworkspace",
        clean: true,
        scheme: "ExoRun",
        output_name: "ExoRun",
        xcargs: "-UseModernBuildSystem=NO",
        export_method: "ad-hoc"
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore") # more information: https://codesigning.guide
    add_badge
    gym(
      workspace: "ExoRun.xcworkspace",
      scheme: "ExoRun",
      xcargs: "-UseModernBuildSystem=NO",
      export_method: "app-store"
    ) # Build your app - more options available
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(type: "appstore")
    gym(
      workspace: "ExoRun.xcworkspace",
      scheme: "ExoRun",
      xcargs: "-UseModernBuildSystem=NO",
      export_method: "app-store"
    )
    deliver(force: true)
  end
end
