# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do

  desc "create an ios ipa file in build folder"
  lane :staging do
    gym(
        workspace: "ExoRun.xcworkspace",
        scheme: "ExoRun",
        xcargs: "-UseNewBuildSystem=NO -allowProvisioningUpdates",
        export_method: "ad-hoc"
    ) # Build your app - more options available
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore") # more information: https://codesigning.guide
    gym(
      workspace: "ExoRun.xcworkspace",
      scheme: "ExoRun",
      xcargs: "-UseNewBuildSystem=NO"
    ) # Build your app - more options available
    pilot
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    match(type: "appstore")
    gym(
      workspace: "ExoRun.xcworkspace",
      scheme: "ExoRun",
      xcargs: "-UseNewBuildSystem=NO"
    )
    deliver(force: true)
  end
end
